/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : Id,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'coverImage' : string,
  'excerpt' : string,
}
export type BlogPostId = bigint;
export type Category = { 'security' : null } |
  { 'secondary' : null } |
  { 'primary' : null } |
  { 'additional' : null };
export type CategoryId = bigint;
export type Category__1 = { 'web' : null } |
  { 'mobile' : null } |
  { 'backend' : null };
export interface Category__2 {
  'id' : Id,
  'sortOrder' : bigint,
  'name' : string,
}
export interface Contact {
  'id' : Id,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
}
export type ContactId = bigint;
export interface Experience {
  'id' : Id,
  'title' : string,
  'duration' : string,
  'sortOrder' : bigint,
  'description' : string,
  'company' : string,
}
export type ExperienceId = bigint;
export type Id = bigint;
export interface Project {
  'id' : Id,
  'title' : string,
  'sortOrder' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'repoUrl' : string,
  'category' : Category__1,
  'liveUrl' : string,
}
export type ProjectId = bigint;
export interface SeoSettings {
  'metaDescription' : string,
  'ogImage' : string,
  'metaTitle' : string,
}
export interface Service {
  'id' : Id,
  'title' : string,
  'sortOrder' : bigint,
  'icon' : string,
  'description' : string,
}
export type ServiceId = bigint;
export interface Skill {
  'id' : Id,
  'sortOrder' : bigint,
  'icon' : string,
  'name' : string,
  'level' : bigint,
  'category' : Category,
}
export type SkillId = bigint;
export interface SocialLink {
  'id' : Id,
  'url' : string,
  'sortOrder' : bigint,
  'platform' : string,
  'isActive' : boolean,
}
export type SocialLinkId = bigint;
export interface Testimonial {
  'id' : Id,
  'content' : string,
  'sortOrder' : bigint,
  'name' : string,
  'role' : string,
  'company' : string,
  'avatarUrl' : string,
  'rating' : bigint,
}
export type TestimonialId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[BlogPost], BlogPostId>,
  'createCategory' : ActorMethod<[Category__2], CategoryId>,
  'createContact' : ActorMethod<[Contact], ContactId>,
  'createExperience' : ActorMethod<[Experience], ExperienceId>,
  'createProject' : ActorMethod<[Project], ProjectId>,
  'createService' : ActorMethod<[Service], ServiceId>,
  'createSkill' : ActorMethod<[Skill], SkillId>,
  'createSocialLink' : ActorMethod<[SocialLink], SocialLinkId>,
  'createTestimonial' : ActorMethod<[Testimonial], TestimonialId>,
  'deleteBlogPost' : ActorMethod<[BlogPostId], undefined>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteContact' : ActorMethod<[ContactId], undefined>,
  'deleteExperience' : ActorMethod<[ExperienceId], undefined>,
  'deleteProject' : ActorMethod<[ProjectId], undefined>,
  'deleteService' : ActorMethod<[ServiceId], undefined>,
  'deleteSkill' : ActorMethod<[SkillId], undefined>,
  'deleteSocialLink' : ActorMethod<[SocialLinkId], undefined>,
  'deleteTestimonial' : ActorMethod<[TestimonialId], undefined>,
  'getActiveProjects' : ActorMethod<[], Array<Project>>,
  'getActiveSocialLinks' : ActorMethod<[], Array<SocialLink>>,
  'getAllBlogPostsAdmin' : ActorMethod<[], Array<BlogPost>>,
  'getAllCategories' : ActorMethod<[], Array<Category__2>>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllExperiences' : ActorMethod<[], Array<Experience>>,
  'getAllProjectsAdmin' : ActorMethod<[], Array<Project>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllSkills' : ActorMethod<[], Array<Skill>>,
  'getAllSocialLinksAdmin' : ActorMethod<[], Array<SocialLink>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBlogPost' : ActorMethod<[BlogPostId], BlogPost>,
  'getBlogPostBySlug' : ActorMethod<[string], BlogPost>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategory' : ActorMethod<[CategoryId], Category__2>,
  'getContact' : ActorMethod<[ContactId], Contact>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'leadsCount' : bigint,
      'servicesCount' : bigint,
      'skillsCount' : bigint,
      'projectsCount' : bigint,
      'testimonialsCount' : bigint,
      'blogsCount' : bigint,
    }
  >,
  'getExperience' : ActorMethod<[ExperienceId], Experience>,
  'getProject' : ActorMethod<[ProjectId], Project>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getSeoSettings' : ActorMethod<[], SeoSettings>,
  'getService' : ActorMethod<[ServiceId], Service>,
  'getSkill' : ActorMethod<[SkillId], Skill>,
  'getSocialLink' : ActorMethod<[SocialLinkId], SocialLink>,
  'getTestimonial' : ActorMethod<[TestimonialId], Testimonial>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPostId, BlogPost], undefined>,
  'updateCategory' : ActorMethod<[CategoryId, Category__2], undefined>,
  'updateExperience' : ActorMethod<[ExperienceId, Experience], undefined>,
  'updateProject' : ActorMethod<[ProjectId, Project], undefined>,
  'updateSeoSettings' : ActorMethod<[SeoSettings], undefined>,
  'updateService' : ActorMethod<[ServiceId, Service], undefined>,
  'updateSkill' : ActorMethod<[SkillId, Skill], undefined>,
  'updateSocialLink' : ActorMethod<[SocialLinkId, SocialLink], undefined>,
  'updateTestimonial' : ActorMethod<[TestimonialId, Testimonial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];