/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Id = IDL.Nat;
export const BlogPost = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Int,
  'coverImage' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const BlogPostId = IDL.Nat;
export const Category__2 = IDL.Record({
  'id' : Id,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
});
export const CategoryId = IDL.Nat;
export const Time = IDL.Int;
export const Contact = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ContactId = IDL.Nat;
export const Experience = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'company' : IDL.Text,
});
export const ExperienceId = IDL.Nat;
export const Category__1 = IDL.Variant({
  'web' : IDL.Null,
  'mobile' : IDL.Null,
  'backend' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'repoUrl' : IDL.Text,
  'category' : Category__1,
  'liveUrl' : IDL.Text,
});
export const ProjectId = IDL.Nat;
export const Service = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const ServiceId = IDL.Nat;
export const Category = IDL.Variant({
  'security' : IDL.Null,
  'secondary' : IDL.Null,
  'primary' : IDL.Null,
  'additional' : IDL.Null,
});
export const Skill = IDL.Record({
  'id' : Id,
  'sortOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'category' : Category,
});
export const SkillId = IDL.Nat;
export const SocialLink = IDL.Record({
  'id' : Id,
  'url' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'platform' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const SocialLinkId = IDL.Nat;
export const Testimonial = IDL.Record({
  'id' : Id,
  'content' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'company' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'rating' : IDL.Nat,
});
export const TestimonialId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SeoSettings = IDL.Record({
  'metaDescription' : IDL.Text,
  'ogImage' : IDL.Text,
  'metaTitle' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func([BlogPost], [BlogPostId], []),
  'createCategory' : IDL.Func([Category__2], [CategoryId], []),
  'createContact' : IDL.Func([Contact], [ContactId], []),
  'createExperience' : IDL.Func([Experience], [ExperienceId], []),
  'createProject' : IDL.Func([Project], [ProjectId], []),
  'createService' : IDL.Func([Service], [ServiceId], []),
  'createSkill' : IDL.Func([Skill], [SkillId], []),
  'createSocialLink' : IDL.Func([SocialLink], [SocialLinkId], []),
  'createTestimonial' : IDL.Func([Testimonial], [TestimonialId], []),
  'deleteBlogPost' : IDL.Func([BlogPostId], [], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteContact' : IDL.Func([ContactId], [], []),
  'deleteExperience' : IDL.Func([ExperienceId], [], []),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'deleteService' : IDL.Func([ServiceId], [], []),
  'deleteSkill' : IDL.Func([SkillId], [], []),
  'deleteSocialLink' : IDL.Func([SocialLinkId], [], []),
  'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
  'getActiveProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getActiveSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
  'getAllBlogPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category__2)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getAllProjectsAdmin' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'getAllSocialLinksAdmin' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBlogPost' : IDL.Func([BlogPostId], [BlogPost], ['query']),
  'getBlogPostBySlug' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategory' : IDL.Func([CategoryId], [Category__2], ['query']),
  'getContact' : IDL.Func([ContactId], [Contact], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'leadsCount' : IDL.Nat,
          'servicesCount' : IDL.Nat,
          'skillsCount' : IDL.Nat,
          'projectsCount' : IDL.Nat,
          'testimonialsCount' : IDL.Nat,
          'blogsCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getExperience' : IDL.Func([ExperienceId], [Experience], ['query']),
  'getProject' : IDL.Func([ProjectId], [Project], ['query']),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getSeoSettings' : IDL.Func([], [SeoSettings], ['query']),
  'getService' : IDL.Func([ServiceId], [Service], ['query']),
  'getSkill' : IDL.Func([SkillId], [Skill], ['query']),
  'getSocialLink' : IDL.Func([SocialLinkId], [SocialLink], ['query']),
  'getTestimonial' : IDL.Func([TestimonialId], [Testimonial], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBlogPost' : IDL.Func([BlogPostId, BlogPost], [], []),
  'updateCategory' : IDL.Func([CategoryId, Category__2], [], []),
  'updateExperience' : IDL.Func([ExperienceId, Experience], [], []),
  'updateProject' : IDL.Func([ProjectId, Project], [], []),
  'updateSeoSettings' : IDL.Func([SeoSettings], [], []),
  'updateService' : IDL.Func([ServiceId, Service], [], []),
  'updateSkill' : IDL.Func([SkillId, Skill], [], []),
  'updateSocialLink' : IDL.Func([SocialLinkId, SocialLink], [], []),
  'updateTestimonial' : IDL.Func([TestimonialId, Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Id = IDL.Nat;
  const BlogPost = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Int,
    'coverImage' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const BlogPostId = IDL.Nat;
  const Category__2 = IDL.Record({
    'id' : Id,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
  });
  const CategoryId = IDL.Nat;
  const Time = IDL.Int;
  const Contact = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ContactId = IDL.Nat;
  const Experience = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'company' : IDL.Text,
  });
  const ExperienceId = IDL.Nat;
  const Category__1 = IDL.Variant({
    'web' : IDL.Null,
    'mobile' : IDL.Null,
    'backend' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'repoUrl' : IDL.Text,
    'category' : Category__1,
    'liveUrl' : IDL.Text,
  });
  const ProjectId = IDL.Nat;
  const Service = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const ServiceId = IDL.Nat;
  const Category = IDL.Variant({
    'security' : IDL.Null,
    'secondary' : IDL.Null,
    'primary' : IDL.Null,
    'additional' : IDL.Null,
  });
  const Skill = IDL.Record({
    'id' : Id,
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'category' : Category,
  });
  const SkillId = IDL.Nat;
  const SocialLink = IDL.Record({
    'id' : Id,
    'url' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'platform' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const SocialLinkId = IDL.Nat;
  const Testimonial = IDL.Record({
    'id' : Id,
    'content' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'company' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const TestimonialId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SeoSettings = IDL.Record({
    'metaDescription' : IDL.Text,
    'ogImage' : IDL.Text,
    'metaTitle' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func([BlogPost], [BlogPostId], []),
    'createCategory' : IDL.Func([Category__2], [CategoryId], []),
    'createContact' : IDL.Func([Contact], [ContactId], []),
    'createExperience' : IDL.Func([Experience], [ExperienceId], []),
    'createProject' : IDL.Func([Project], [ProjectId], []),
    'createService' : IDL.Func([Service], [ServiceId], []),
    'createSkill' : IDL.Func([Skill], [SkillId], []),
    'createSocialLink' : IDL.Func([SocialLink], [SocialLinkId], []),
    'createTestimonial' : IDL.Func([Testimonial], [TestimonialId], []),
    'deleteBlogPost' : IDL.Func([BlogPostId], [], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteContact' : IDL.Func([ContactId], [], []),
    'deleteExperience' : IDL.Func([ExperienceId], [], []),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'deleteService' : IDL.Func([ServiceId], [], []),
    'deleteSkill' : IDL.Func([SkillId], [], []),
    'deleteSocialLink' : IDL.Func([SocialLinkId], [], []),
    'deleteTestimonial' : IDL.Func([TestimonialId], [], []),
    'getActiveProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getActiveSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
    'getAllBlogPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category__2)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getAllProjectsAdmin' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'getAllSocialLinksAdmin' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBlogPost' : IDL.Func([BlogPostId], [BlogPost], ['query']),
    'getBlogPostBySlug' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategory' : IDL.Func([CategoryId], [Category__2], ['query']),
    'getContact' : IDL.Func([ContactId], [Contact], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'leadsCount' : IDL.Nat,
            'servicesCount' : IDL.Nat,
            'skillsCount' : IDL.Nat,
            'projectsCount' : IDL.Nat,
            'testimonialsCount' : IDL.Nat,
            'blogsCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getExperience' : IDL.Func([ExperienceId], [Experience], ['query']),
    'getProject' : IDL.Func([ProjectId], [Project], ['query']),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getSeoSettings' : IDL.Func([], [SeoSettings], ['query']),
    'getService' : IDL.Func([ServiceId], [Service], ['query']),
    'getSkill' : IDL.Func([SkillId], [Skill], ['query']),
    'getSocialLink' : IDL.Func([SocialLinkId], [SocialLink], ['query']),
    'getTestimonial' : IDL.Func([TestimonialId], [Testimonial], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBlogPost' : IDL.Func([BlogPostId, BlogPost], [], []),
    'updateCategory' : IDL.Func([CategoryId, Category__2], [], []),
    'updateExperience' : IDL.Func([ExperienceId, Experience], [], []),
    'updateProject' : IDL.Func([ProjectId, Project], [], []),
    'updateSeoSettings' : IDL.Func([SeoSettings], [], []),
    'updateService' : IDL.Func([ServiceId, Service], [], []),
    'updateSkill' : IDL.Func([SkillId, Skill], [], []),
    'updateSocialLink' : IDL.Func([SocialLinkId, SocialLink], [], []),
    'updateTestimonial' : IDL.Func([TestimonialId, Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };