/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ServiceId = bigint;
export interface SeoSettings {
    metaDescription: string;
    ogImage: string;
    metaTitle: string;
}
export type Time = bigint;
export interface Contact {
    id: ContactId;
    name: string;
    createdAt: Time;
    email: string;
    message: string;
}
export type SkillId = bigint;
export interface SocialLink {
    id: SocialLinkId;
    url: string;
    sortOrder: bigint;
    platform: string;
    isActive: boolean;
}
export interface Service {
    id: ServiceId;
    title: string;
    sortOrder: bigint;
    icon: string;
    description: string;
}
export interface BlogPost {
    id: BlogPostId;
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    tags: Array<string>;
    publishedAt: Time;
    coverImage: string;
    excerpt: string;
}
export type ExperienceId = bigint;
export interface Category__2 {
    id: CategoryId;
    sortOrder: bigint;
    name: string;
}
export type BlogPostId = bigint;
export interface Skill {
    id: SkillId;
    sortOrder: bigint;
    icon: string;
    name: string;
    level: bigint;
    category: Category;
}
export interface Experience {
    id: ExperienceId;
    title: string;
    duration: string;
    sortOrder: bigint;
    description: string;
    company: string;
}
export type ProjectId = bigint;
export type SocialLinkId = bigint;
export type ContactId = bigint;
export type CategoryId = bigint;
export interface Project {
    id: ProjectId;
    title: string;
    sortOrder: bigint;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    imageUrl: string;
    repoUrl: string;
    category: Category__1;
    liveUrl: string;
}
export type TestimonialId = bigint;
export interface UserProfile {
    name: string;
}
export interface Testimonial {
    id: TestimonialId;
    content: string;
    sortOrder: bigint;
    name: string;
    role: string;
    company: string;
    avatarUrl: string;
    rating: bigint;
}
export enum Category {
    security = "security",
    secondary = "secondary",
    primary = "primary",
    additional = "additional"
}
export enum Category__1 {
    web = "web",
    mobile = "mobile",
    backend = "backend"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBlogPost(blogPost: BlogPost): Promise<BlogPostId>;
    createCategory(category: Category__2): Promise<CategoryId>;
    createContact(contact: Contact): Promise<ContactId>;
    createExperience(experience: Experience): Promise<ExperienceId>;
    createProject(project: Project): Promise<ProjectId>;
    createService(service: Service): Promise<ServiceId>;
    createSkill(skill: Skill): Promise<SkillId>;
    createSocialLink(socialLink: SocialLink): Promise<SocialLinkId>;
    createTestimonial(testimonial: Testimonial): Promise<TestimonialId>;
    deleteBlogPost(id: BlogPostId): Promise<void>;
    deleteCategory(id: CategoryId): Promise<void>;
    deleteContact(id: ContactId): Promise<void>;
    deleteExperience(id: ExperienceId): Promise<void>;
    deleteProject(id: ProjectId): Promise<void>;
    deleteService(id: ServiceId): Promise<void>;
    deleteSkill(id: SkillId): Promise<void>;
    deleteSocialLink(id: SocialLinkId): Promise<void>;
    deleteTestimonial(id: TestimonialId): Promise<void>;
    getActiveProjects(): Promise<Array<Project>>;
    getActiveSocialLinks(): Promise<Array<SocialLink>>;
    getAllBlogPostsAdmin(): Promise<Array<BlogPost>>;
    getAllCategories(): Promise<Array<Category__2>>;
    getAllContacts(): Promise<Array<Contact>>;
    getAllExperiences(): Promise<Array<Experience>>;
    getAllProjectsAdmin(): Promise<Array<Project>>;
    getAllServices(): Promise<Array<Service>>;
    getAllSkills(): Promise<Array<Skill>>;
    getAllTestimonials(): Promise<Array<Testimonial>>;
    getBlogPost(id: BlogPostId): Promise<BlogPost>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategory(id: CategoryId): Promise<Category__2>;
    getContact(id: ContactId): Promise<Contact>;
    getDashboardStats(): Promise<{
        leadsCount: bigint;
        servicesCount: bigint;
        skillsCount: bigint;
        projectsCount: bigint;
        testimonialsCount: bigint;
        blogsCount: bigint;
    }>;
    getExperience(id: ExperienceId): Promise<Experience>;
    getProject(id: ProjectId): Promise<Project>;
    getPublishedBlogPosts(): Promise<Array<BlogPost>>;
    getSeoSettings(): Promise<SeoSettings>;
    getService(id: ServiceId): Promise<Service>;
    getSkill(id: SkillId): Promise<Skill>;
    getSocialLink(id: SocialLinkId): Promise<SocialLink>;
    getTestimonial(id: TestimonialId): Promise<Testimonial>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBlogPost(id: BlogPostId, blogPost: BlogPost): Promise<void>;
    updateCategory(id: CategoryId, category: Category__2): Promise<void>;
    updateExperience(id: ExperienceId, experience: Experience): Promise<void>;
    updateProject(id: ProjectId, project: Project): Promise<void>;
    updateSeoSettings(newSettings: SeoSettings): Promise<void>;
    updateService(id: ServiceId, service: Service): Promise<void>;
    updateSkill(id: SkillId, skill: Skill): Promise<void>;
    updateSocialLink(id: SocialLinkId, socialLink: SocialLink): Promise<void>;
    updateTestimonial(id: TestimonialId, testimonial: Testimonial): Promise<void>;
}
import type { Category as _Category, Category__1 as _Category__1, Project as _Project, ProjectId as _ProjectId, Skill as _Skill, SkillId as _SkillId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBlogPost(arg0: BlogPost): Promise<BlogPostId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0);
            return result;
        }
    }
    async createCategory(arg0: Category__2): Promise<CategoryId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createContact(arg0: Contact): Promise<ContactId> {
        if (this.processError) {
            try {
                const result = await this.actor.createContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContact(arg0);
            return result;
        }
    }
    async createExperience(arg0: Experience): Promise<ExperienceId> {
        if (this.processError) {
            try {
                const result = await this.actor.createExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExperience(arg0);
            return result;
        }
    }
    async createProject(arg0: Project): Promise<ProjectId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_Project_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_Project_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createService(arg0: Service): Promise<ServiceId> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(arg0);
            return result;
        }
    }
    async createSkill(arg0: Skill): Promise<SkillId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSkill(to_candid_Skill_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSkill(to_candid_Skill_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSocialLink(arg0: SocialLink): Promise<SocialLinkId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSocialLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSocialLink(arg0);
            return result;
        }
    }
    async createTestimonial(arg0: Testimonial): Promise<TestimonialId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestimonial(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: BlogPostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: CategoryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteContact(arg0: ContactId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteExperience(arg0: ExperienceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExperience(arg0);
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteService(arg0: ServiceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async deleteSkill(arg0: SkillId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSkill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSkill(arg0);
            return result;
        }
    }
    async deleteSocialLink(arg0: SocialLinkId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSocialLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSocialLink(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: TestimonialId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async getActiveProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProjects();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProjects();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveSocialLinks(): Promise<Array<SocialLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSocialLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSocialLinks();
            return result;
        }
    }
    async getAllBlogPostsAdmin(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPostsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPostsAdmin();
            return result;
        }
    }
    async getAllCategories(): Promise<Array<Category__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return result;
        }
    }
    async getAllExperiences(): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExperiences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExperiences();
            return result;
        }
    }
    async getAllProjectsAdmin(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjectsAdmin();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjectsAdmin();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return result;
        }
    }
    async getAllSkills(): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSkills();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSkills();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestimonials();
            return result;
        }
    }
    async getBlogPost(arg0: BlogPostId): Promise<BlogPost> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: CategoryId): Promise<Category__2> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return result;
        }
    }
    async getContact(arg0: ContactId): Promise<Contact> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<{
        leadsCount: bigint;
        servicesCount: bigint;
        skillsCount: bigint;
        projectsCount: bigint;
        testimonialsCount: bigint;
        blogsCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getExperience(arg0: ExperienceId): Promise<Experience> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperience(arg0);
            return result;
        }
    }
    async getProject(arg0: ProjectId): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_Project_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_Project_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBlogPosts();
            return result;
        }
    }
    async getSeoSettings(): Promise<SeoSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeoSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeoSettings();
            return result;
        }
    }
    async getService(arg0: ServiceId): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return result;
        }
    }
    async getSkill(arg0: SkillId): Promise<Skill> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkill(arg0);
                return from_candid_Skill_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkill(arg0);
            return from_candid_Skill_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSocialLink(arg0: SocialLinkId): Promise<SocialLink> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialLink(arg0);
            return result;
        }
    }
    async getTestimonial(arg0: TestimonialId): Promise<Testimonial> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonial(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: BlogPostId, arg1: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: CategoryId, arg1: Category__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateExperience(arg0: ExperienceId, arg1: Experience): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExperience(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExperience(arg0, arg1);
            return result;
        }
    }
    async updateProject(arg0: ProjectId, arg1: Project): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_Project_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_Project_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSeoSettings(arg0: SeoSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSeoSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSeoSettings(arg0);
            return result;
        }
    }
    async updateService(arg0: ServiceId, arg1: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1);
            return result;
        }
    }
    async updateSkill(arg0: SkillId, arg1: Skill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkill(arg0, to_candid_Skill_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkill(arg0, to_candid_Skill_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSocialLink(arg0: SocialLinkId, arg1: SocialLink): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSocialLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSocialLink(arg0, arg1);
            return result;
        }
    }
    async updateTestimonial(arg0: TestimonialId, arg1: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Category__1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category__1): Category__1 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Skill_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Skill): Skill {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    title: string;
    sortOrder: bigint;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    imageUrl: string;
    repoUrl: string;
    category: _Category__1;
    liveUrl: string;
}): {
    id: ProjectId;
    title: string;
    sortOrder: bigint;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    imageUrl: string;
    repoUrl: string;
    category: Category__1;
    liveUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        sortOrder: value.sortOrder,
        tags: value.tags,
        description: value.description,
        isActive: value.isActive,
        imageUrl: value.imageUrl,
        repoUrl: value.repoUrl,
        category: from_candid_Category__1_n14(_uploadFile, _downloadFile, value.category),
        liveUrl: value.liveUrl
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SkillId;
    sortOrder: bigint;
    icon: string;
    name: string;
    level: bigint;
    category: _Category;
}): {
    id: SkillId;
    sortOrder: bigint;
    icon: string;
    name: string;
    level: bigint;
    category: Category;
} {
    return {
        id: value.id,
        sortOrder: value.sortOrder,
        icon: value.icon,
        name: value.name,
        level: value.level,
        category: from_candid_Category_n19(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    web: null;
} | {
    mobile: null;
} | {
    backend: null;
}): Category__1 {
    return "web" in value ? Category__1.web : "mobile" in value ? Category__1.mobile : "backend" in value ? Category__1.backend : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    security: null;
} | {
    secondary: null;
} | {
    primary: null;
} | {
    additional: null;
}): Category {
    return "security" in value ? Category.security : "secondary" in value ? Category.secondary : "primary" in value ? Category.primary : "additional" in value ? Category.additional : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Skill>): Array<Skill> {
    return value.map((x)=>from_candid_Skill_n17(_uploadFile, _downloadFile, x));
}
function to_candid_Category__1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category__1): _Category__1 {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Project_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Project): _Project {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Skill_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Skill): _Skill {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProjectId;
    title: string;
    sortOrder: bigint;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    imageUrl: string;
    repoUrl: string;
    category: Category__1;
    liveUrl: string;
}): {
    id: _ProjectId;
    title: string;
    sortOrder: bigint;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    imageUrl: string;
    repoUrl: string;
    category: _Category__1;
    liveUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        sortOrder: value.sortOrder,
        tags: value.tags,
        description: value.description,
        isActive: value.isActive,
        imageUrl: value.imageUrl,
        repoUrl: value.repoUrl,
        category: to_candid_Category__1_n5(_uploadFile, _downloadFile, value.category),
        liveUrl: value.liveUrl
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: SkillId;
    sortOrder: bigint;
    icon: string;
    name: string;
    level: bigint;
    category: Category;
}): {
    id: _SkillId;
    sortOrder: bigint;
    icon: string;
    name: string;
    level: bigint;
    category: _Category;
} {
    return {
        id: value.id,
        sortOrder: value.sortOrder,
        icon: value.icon,
        name: value.name,
        level: value.level,
        category: to_candid_Category_n9(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    security: null;
} | {
    secondary: null;
} | {
    primary: null;
} | {
    additional: null;
} {
    return value == Category.security ? {
        security: null
    } : value == Category.secondary ? {
        secondary: null
    } : value == Category.primary ? {
        primary: null
    } : value == Category.additional ? {
        additional: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category__1): {
    web: null;
} | {
    mobile: null;
} | {
    backend: null;
} {
    return value == Category__1.web ? {
        web: null
    } : value == Category__1.mobile ? {
        mobile: null
    } : value == Category__1.backend ? {
        backend: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
